//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeHandlerNET.CommSvcReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.ICommSvc")]
    public interface ICommSvc
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICommSvc/SendMessage", ReplyAction = "http://tempuri.org/ICommSvc/SendMessageResponse")]
        void SendMessage(string user, string message);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICommSvc/GetInfo", ReplyAction = "http://tempuri.org/ICommSvc/GetInfoResponse")]
        object GetInfo(string user, string message);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommSvcChannel : SkypeHandlerNET.CommSvcReference.ICommSvc, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommSvcClient : System.ServiceModel.ClientBase<SkypeHandlerNET.CommSvcReference.ICommSvc>, SkypeHandlerNET.CommSvcReference.ICommSvc
    {

        public CommSvcClient()
        {
        }

        public CommSvcClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CommSvcClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CommSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CommSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public void SendMessage(string user, string message)
        {
            base.Channel.SendMessage(user, message);
        }

        public object GetInfo(string user, string message)
        {
            return base.Channel.GetInfo(user, message);
        }
    }
}
